# Generated by Django 5.2.4 on 2025-09-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='description',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='longevity',
            field=models.CharField(choices=[('contractual', 'Contractual'), ('permanent', 'Permanent')], db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='posted_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='title',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='type',
            field=models.CharField(choices=[('full-time', 'Full-Time'), ('part-time', 'Part-Time')], db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='working_area',
            field=models.CharField(choices=[('onsite', 'Onsite'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], db_index=True, max_length=20),
        ),
    ]
