# Generated by Django 5.2.4 on 2025-09-23 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_alter_applications_status_alter_jobs_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application', to='business.applications'),
        ),
    ]
