# Generated by Django 5.2.6 on 2025-09-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_alter_notifications_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
